Update inputForm and reportHistory pages
Kittinske15/reimburse-medical-expense pull request #3
Opened 2020-08-26 06:18 UTC by Kittinske15

1. report history specify by userId
2. responsive with tablet and mobile 
3. can route to any page

2020-08-26 07:32 UTC, bankkeez requested changes

2020-08-26 07:32 UTC, bankkeez commented on src/App.css
> +    width: 1000px;
maybe `width: 100%` 🧐

2020-08-26 07:54 UTC, Kittinske15 commented on src/App.css
> +    width: 1000px;
noted

2020-09-18 09:57 UTC, kimvcp requested changes

2020-09-18 09:57 UTC, kimvcp commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
expense.name is better?

2020-09-18 09:59 UTC, kimvcp commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
Is it possible to handle user's full name from React component

2020-09-18 10:59 UTC, bankkeez commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
@kimvcp Please be more detailed in your question, what do you mean by `expense.name` is better when @Kittinske15 is changing that **LOC**. 🧐

2020-09-18 11:06 UTC, bankkeez requested changes

2020-09-18 11:06 UTC, bankkeez commented on src/App.css
> +    padding: 5px 200px 5px 200px;
How about this 🤔:
```suggestion
    padding: 5px 200px;
```

2020-09-18 11:06 UTC, bankkeez commented on src/App.css
> +    width: 1000px;
I think `width: 100%` might fit better, since `1000px` is a fixed value and might break something 😬

2020-09-18 11:06 UTC, bankkeez commented on src/App.js
> +let DEV_URL="https://medical-requistion.herokuapp.com";
Maybe go with this to prevent the url from mutation.
```suggestion
const DEV_URL="https://medical-requistion.herokuapp.com";
```

2020-09-18 11:06 UTC, bankkeez commented on src/components/LoginRegister.jsx
> +    console.log(LoginHelper.validateUser("w", "w"));
A reminder here, in production mode remove this 😚

2020-09-18 11:44 UTC, kimvcp commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
My point is to convert from `expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1]` to `expense.name` , then handle splitting logic in React Component instead. Since it allows you to log message in `componentDidMount()`, it would be better to ensure that `expense.user.displayName` exists before passing it to other function.

2020-09-18 19:01 UTC, bankkeez commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
@kimvcp Love this explicit, I also agree with him. 🦾

2020-09-21 03:20 UTC, Kittinske15 commented on src/model/Expense.js
> +    name: expense.user.displayName.split(" ")[0] + " " + expense.user.displayName.split(" ")[1],
noted

2020-09-21 10:04 UTC, kimvcp approved these changes

2020-09-21 10:21 UTC, bankkeez approved these changes

2020-09-25 06:18 UTC, merged